config/routes.rb
Bikerlink::Application.routes.draw do
  devise_for :bikers, controllers: {
    registrations: 'bikers/registrations'
  }

  get 'home/index'

  root to: 'home#index'

  resources :bikers do
    patch :activate
    patch :deactivate
    patch :promote
    patch :demote
    post :search
  end

  resources :bikes

  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<% if current_biker %>
  <%= render 'bikers/shared/search' %>
<% end %>

<p>Welcome to Biker Link.</p>

<p style="font-style: italic;">NOTE: This website is not yet fully functional, and is still in (rapid) development before it is officially open for use.  Signing up at this time without being specifically asked to do so for testing purposes is probably a bad idea.</p>

<p>Denizens of the <code>##motorcycles</code> channel on Freenode are encouraged to sign up for accounts here, write up whatever profile text they like, and add bikes they own and ride.  The purpose of this is to provide a way for people in that channel to share information about the motorcycles they love and about themselves, and to foster more of a feeling of community by helping people connect with each other within that community.</p>

<p>At this time, the Biker Link site is only intended for use by the above mentioned IRC channel.  New accounts do not become visible profiles until they have been activated by the site admin, and the only official way to get validated for account activation at this time is to ask the site admin to activate the account in IRC.  Account names, furthermore, must be the same as registered IRC names to be activated.  If an account name you choose is "owned" by some other IRC user on Freenode, that account may be deleted.</p>

<p>For those familiar with IRC, you can connect to irc.freenode.net as detailed on the <%= link_to 'Freenode website', 'https://freenode.net/kb/answer/chat' %> using the IRC client of your preference, then join the <code>##motorcycles</code> channel, and get to know people there.</p>

<p>There is also a <%= link_to 'Freenode Webchat', 'https://webchat.freenode.net/' %> client that can be used by those not so knowledgeable or dedicated as to have an IRC client installed somewhere.  That may help you get started if this community interests you and you are not familiar with IRC, which stands for "Internet Relay Chat".</p>

<div class="signature">- <%= link_to 'apotheon', biker_path('apotheon') %></div>